/* GENERATED BY assets/og/build.sh — DO NOT EDIT BY HAND.
 *
 * The card Facebook, LinkedIn, X, Slack, WhatsApp and iMessage show when
 * somebody posts a link to this site. To change it, edit assets/og/card.html
 * or assets/og/alt.txt and re-run that script; its header explains why this
 * file exists instead of Next's opengraph-image file convention.
 *
 * The size is the real pixel size of the file, which is 2x the 1200x630 the
 * card is laid out at — the platforms treat 1200x630 as a floor and are all
 * read on retina displays. assets/og/build.sh explains that and the format.
 *
 * `v` is the image's own content hash. All of those platforms cache a share
 * image by URL and never come back to check, so the URL has to change when the
 * picture does.
 */
export const OG_IMAGE = {
  url: "/og.jpg?v=9b9cdae4b6",
  width: 2400,
  height: 1260,
  type: "image/jpeg",
  alt: "The Lampsill mark — an arched window with one pane lit — on a dark ground, beside the words: if their phone goes quiet, Lampsill tells you.",
} as const;
